/*
   This software Connector and its source code are the property of Contxtful Technologies Inc. Use of this
   script is Subject to the terms and conditions of the License Agreement.

   As a subscriber, you agree that you are solely responsible for providing all appropriate and legally
   required disclosures pertaining to the use and removal of the Connector(s) and obtain any legally required
   consents as needed, and you agree that it will defend, indemnify and hold Contxtful Technologies Inc.
   harmless from and against any and all third-party claims stemming from or related to the use of Tags as
   provided herein.
 */
var Contxtful=new __contxtful__;
function __contxtful__(){function Sa(a,b){b="https://ad.doubleclick.net/ddm/activity/src="+H.fld;b=b+";type="+H.type;b+=";cat=";target1=";dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;gdpr=;gdpr_consent=;ord=1?";let c=b+H.cat1+target1;if(!va)try{wa("GET",c,!0).send()}catch(d){console.log("Contxtful.Api log:",d)}if(33<a&&(a=b+H.cat2+target1,!va))try{wa("GET",a,!0).send()}catch(d){console.log("Contxtful.Api log:",d)}}function xa(){var a=new Date;return a.getFullYear()+"-"+("0"+(a.getMonth()+
1)).slice(-2)+"-"+("0"+a.getDate()).slice(-2)+" "+("0"+a.getHours()).slice(-2)+":"+("0"+a.getMinutes()).slice(-2)+":"+("0"+a.getSeconds()).slice(-2)+"."+(a.getMilliseconds()+"000").slice(0,3)}function na(){console.log(arguments);v.clc+=1}function x(a,b){if("function"===typeof rb){var c=rb();if("true"==c.Override&&c.hasOwnProperty(a)&&c[a].localeCompare("N_A"))return/^\d+$/.test(c[a])?parseInt(c[a],10):c[a]}return b}function X(){return"high-precision"===R}function Y(){return"low-latency"===R}function oa(a){sessionStorage.setItem("ctxtflrec",
a);a=Date.now()+3E4;sessionStorage.setItem("ctxtflexp",a)}function ya(){return"undefined"!==typeof contxtful_config}function sb(){console.log("CONTXTFUL: GetReceptivity is not available in","current configuration. Please contact us at support@contxtful.com.")}function rb(){return{Override:"true",Percentage:"1",Delay:"8",WindowSize:"1000",Recep:"Y",WindowSize_fov:"N_A",Freqency_fov:"N_A",WindowSize_pointer:"N_A",
Freqency_pointer:"N_A",WindowSize_screen:"N_A",lookalikeParameter:"{'M':'N','D':'N','W':'cz0yPxUxNUhZOUM/TEJqUC4xcQ=='}",PostDomain:"N_A",PostPath:"N_A",DesktopPercentage:"N_A",DesktopMaxPost:"N_A",DesktopEnabled:"true",CreationTimeStamp:"11-21-2022-20:18:17",CertificationMode:"legacy"}}function E(a){var b={};a.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(c,d,f){b[d]=f});return b}function Sb(){return"yxxxyxxxyxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})}function Tb(){var a=new Date;a.getFullYear();a.getMonth();a.getDate();return Sb()}function tb(a,b=100){return Math.round(Math.random()*b)<a?!0:!1}function ub(a){var b=a.byteLength,c=new Uint8Array(a),d=0;return{GetArrSize:function(){for(var f=0,e=3;0<=e;e--)f+=c[d+e],0<e&&(f<<=8);d+=4;return f<b?f:0},GetStr:function(f){for(var e=[],k=0;k<f;k++)e.push(String.fromCharCode(c[d++]));return e.join("")},GetArray:function(f,e){for(var k=
0;k<e;k++)f[k]=c[d++]}}}function Ta(a,b){function c(g){for(var h=0;4>h;h++){var m=g&255;e[k++]=m;g=(g-m)/256}}function d(g){if("undefined"!==typeof g&&g.length)for(var h=0;h<g.length;h++)e[k++]=g.charCodeAt(h)}Object.keys||(Object.keys=function(){var g=Object.prototype.hasOwnProperty,h=!{toString:null}.propertyIsEnumerable("toString"),m="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),n=m.length;return function(p){if("function"!==typeof p&&
("object"!==typeof p||null===p))throw new TypeError("Object.keys called on non-object");var q=[],w;for(w in p)g.call(p,w)&&q.push(w);if(h)for(w=0;w<n;w++)g.call(p,m[w])&&q.push(m[w]);return q}}());b=function(g){for(var h=Object.keys(g),m=0,n,p,q=0;q<h.length;q++)p=h[q],n=p.length,p=g[h[q]],p="undefined"!==typeof p?p.length:0,n&&p&&(m+=n+p+2);return m+4+4+9+9}(b);a+=b;var f=new ArrayBuffer(a),e=new Uint8Array(f),k=0;c(b);c(a);d("Contxtful");return{AddObj:function(g){for(var h=Object.keys(g),m=0;m<
h.length;m++){var n=h[m],p=g[h[m]];if("undefined"!==typeof p)if(n.length&&p.length){for(var q=0;q<n.length;q++)e[k++]=n.charCodeAt(q);e[k++]=61;for(q=0;q<p.length;q++)e[k++]=p.charCodeAt(q);m!=h.length-1?e[k++]=38:e[k++]=0}else m==h.length-1&&(e[k?k-1:0]=0)}d("Contxtful")},Add32Int:c,AddString:d,AddFloatArray:function(g){g=new Float32Array(g);g=new Uint8Array(g.buffer);for(var h=0;h<g.length;h++)e[k++]=g[h]},AddUintArray:function(g){g=new Uint32Array(g);g=new Uint8Array(g.buffer);for(var h=0;h<g.length;h++)e[k++]=
g[h]},AddFloat32Array:function(g){g=new Uint8Array(g.buffer);for(var h=0;h<g.length;h++)e[k++]=g[h]},AddUint8Array:function(g){for(var h=0;h<g.length;h++)e[k++]=g[h]},ReOrderArr:function(g,h,m){for(var n=0;n<g.length;n++)h[n]=g[m],m=(m+1)%g.length},GetSize:function(){return k},GetBuffer:function(){var g=new ArrayBuffer(k);g=new Uint8Array(g);for(var h=0;h<g.length;h++)g[h]=e[h];return g}}}function Ub(){var a=E(F);Object.keys(a).forEach(function(b){I[b]=a[b]});I.scriptSrc=F}function pa(a){return"undefined"!==
typeof a?0==Object.keys(a).length?"":JSON.stringify(a):"undefined"}function wa(a,b,c){var d=new XMLHttpRequest;"withCredentials"in d?(d.open(a,b,c),c&&(d.responseType="arraybuffer"),d.setRequestHeader("Content-type","application/octet-stream")):"undefined"!=typeof XDomainRequest?(d=new XDomainRequest,d.open(a,b,c)):d=null;return d}function vb(a,b){var c=ub(a),d=c.GetArrSize();d=c.GetStr(d);0==b&&(Ua=c.GetArrSize(),P=new Uint8Array(Ua),c.GetArray(P,Ua));if(d)return b=JSON.parse(d),"undefined"!==typeof b?
b:a}function Vb(a,b=!0){var c=Ta(0,a);c.AddObj(a);a=c.GetBuffer();wb(!0,!0,a,!0,!1,b)}function Va(a="WEB_TRAFFIC_POST",b=""){a={url:encodeURIComponent(window.location.href),originURL:encodeURIComponent(document.referrer),key:qa+"_TRAFFIC",eDesc:a,userIdInternal:l.userIdInternal,userIdClient:l.userIdClient,tBrowser:xa(),other:encodeURIComponent(b)};1==Wa&&(a.Acq="N");Vb(a)}function Wb(a="FIRST"){I.creationDate=Xb;t({noRawData:!0,async:!0,CtxtEvent:a});["creationDate","w","y","z"].forEach(b=>{delete I[b]})}
function Yb(a,b){return X()?-1!=["TRIGGER","MANUAL","FIRST"].indexOf(a)||-1!=["TRAFFIC"].indexOf(a)&&!b:!0}function t({CtxtEvent:a="NONE",autopost:b=!1,async:c=!0,noRawData:d=!1,dataSize:f=0}){var e,k,g,h,m,n,p,q;if(1!=t.stop&&Yb(a,d)){l.Acq="Y";1==Wa&&"TRIGGER"!=a&&"FIRST"!=a&&(l.Acq="N");"undefined"==typeof t.counter&&(t.counter=0);if(1==Zb)if(t.counter==za-1){if(ra(),"STOP"!=a){t.stop=!0;return}}else if(t.counter>=za)return;1==xb&&(-1!==["FIRST","STOP","TRIGGER","MANUAL"].indexOf(a)||5>t.counter||
1==yb?Ub():I={});I.ctxtpc=t.counter;l.postCount=t.counter;1==b&&setTimeout(function(){t({autopost:b,noRawData:d,async:c})},250);l.tBrowser=xa();l.other=pa(I);l.uField=pa(Aa);l.cParam=pa(Ba);var w=1E3*((new Date).getTime()-M);if(w<2E3*J||1==d){var C=0;l.ctxtReq=pa(zb);l.eDesc="WEB_"+a+"_POST";0==t.counter?l.key=qa+"_STATS":"RUNTIME"===a?l.eDesc="WEB_RUNTIME":"RUNTIME"!==a&&"FIRST_POST"!==a&&"TRAFFIC"!==a&&r!=D&&(w=w*D/r);l.url="";l.originUrl="";l.uaStr="";if("FIRST"==a||"STOP"==a||5>t.counter||1==
yb)l.url=window.location.href,l.originUrl=document.referrer,l.uaStr="NaN";for(var u in l)l[u]=encodeURIComponent(l[u]);if(0==d){l.key="TRAFFIC"==a||"MANUAL"==a?qa+"_"+a:qa+"_STATS";u=function($b){return 0!=$b};var B;var G=0;if(Z.some(u)||sa.some(u)||ta.some(u)){v.sensorsWorking=!0;var aa=1}else v.sensorsWorking=!1,aa=0;u=Ca.some(u)||Da.some(u)||Ea.some(u)?1:0;for(B=G=0;B<Z.length;B++)0==Z[B]&&0==sa[B]&&0==ta[B]||G++;v.sensorHasEnoughSampleNonZero=1==ba?G>ac?!0:!1:G>bc?!0:!1;B=u&aa;G=3*(aa+u+B);1==
ba&&0==xb&&ra();var ca=f;if("TRIGGER"==a||"MANUAL"==a)ca=D;C="undefined"!==typeof P&&0<P.length?4*G*ca+56+P.length:4*G*ca+56;var Fa=g=k=G=e=0;var Ab=q=p=n=m=h=void 0;1==da&&"TRIGGER"!=a&&"MANUAL"!=a&&(h=Ga.read(),Ga.resetBuffers(),m=Ha.read(),Ha.resetBuffers(),n=Ia.read(),Ia.resetBuffers(),p=Ja.read(),Ja.resetBuffers(),e=1<Xa/J?w:Xa/J*w,G=h.length,q=Ka.read(),Ka.resetBuffers(),Ab=La.read(),La.resetBuffers(),k=1<Ya/J?w:Ya/J*w,g=q.length,Fa=S.length,a=16*G+8*g,a+=20*Fa,C+=a);a=Ta(C,l);a.AddObj(l);a.Add32Int(10);
a.Add32Int(u*ca);a.Add32Int(aa*ca);a.Add32Int(B*ca);a.Add32Int(0);a.Add32Int(0);a.Add32Int(0);a.Add32Int(1);a.Add32Int(G);a.Add32Int(g);a.Add32Int(Fa);a.Add32Int(w);a.Add32Int(e);a.Add32Int(k);u&&(N(Ca,f,a),N(Da,f,a),N(Ea,f,a));aa&&(N(Z,f,a),N(sa,f,a),N(ta,f,a));B&&(N(Za,f,a),N($a,f,a),N(ab,f,a));0<G&&(a.AddFloat32Array(h),a.AddFloat32Array(m),a.AddFloat32Array(n),a.AddFloat32Array(p));0<g&&(a.AddFloat32Array(q),a.AddFloat32Array(Ab));if(0<Fa){a.AddFloatArray(ea);a.AddFloatArray(S);a.AddFloatArray(fa);
for(B=0;B<O.length;B++)O[B]=1E3*(O[B]-M);a.AddUintArray(O);a.AddFloatArray(ha)}"undefined"!==typeof P&&0<P.length&&a.AddUint8Array(P)}else a=Ta(C,l),a.AddObj(l);a.GetSize();if(d||aa||G)f=a.GetBuffer(),wb(c,ba,f,d,!0)}}}function wb(a,b,c,d,f,e=!0,k=bb,g=cb){v.noSensordevice="WEB_FIRST_POST"!=l.eDesc?!1:!0;var h="";h="here"==g?window.location.host:g;1==b&&(h="here"==Ma?window.location.host:Ma);var m=wa("POST","//"+h.toString()+"/"+k,a);if(!m)throw Error("CORS not supported");a&&(m.performAfterPostAction=
e,m.userIdInternal=l.userIdInternal,m.eDesc=l.eDesc,m.POST_SENT_TIME=cc,m.onload=function(){var n=vb(m.response,d);"undefined"!==typeof n&&m.performAfterPostAction&&T(n)});m.send(c);v.ptim.push([l.eDesc,(new Date).getTime()]);1==f&&(t.counter+=1);if(!a&&e&&"undefined"!==typeof m.response){a=m.response.length-8;b=new ArrayBuffer(a+8);b=new Uint8Array(b);for(c=0;c<a+8;c++)b[c]=m.response.charCodeAt(c)&255;for(c=0;4>c;c++)f=a&255,a>>=8,b[c]=f;a=vb(b,d);"undefined"!==typeof a&&T(a);return a}}function N(a,
b,c,d=-1){-1!=d?c.AddFloat32Array(a.slice(b,d)):(b!=D&&c.AddFloat32Array(a.slice(b,D)),0!=b&&(b>D&&(b=D),c.AddFloat32Array(a.slice(0,b))))}function dc(){K>J&&(M+=K-J);t({async:ia,CtxtEvent:"RUNTIME",dataSize:0});M=(new Date).getTime();t.counter>=db&&(clearInterval(U),U=null,t({noRawData:!0,async:!0,CtxtEvent:"STOP"}))}function eb(){L=!0;null===U&&1==da&&(M=(new Date).getTime(),xa(),Bb(),100>Na&&!tb(Na)||(Wa=!1,U=setInterval(dc,K)))}function fb(a){!1!==Oa&&(clearTimeout(Oa),Oa=!1);0==r&&(M=(new Date).getTime(),
xa(),1==da&&Bb());null==a.acceleration.x&&null==a.acceleration.y&&null==a.acceleration.z&&Q&&(Sa(Math.floor(100*Math.random()),"handleMotionEvent"),Q=!1);null==a.acceleration.x&&null==a.acceleration.y&&null==a.acceleration.z&&1==da?eb():L=!1;var b=gb?-1:1;null!=a.accelerationIncludingGravity?(Z[r]=b*a.accelerationIncludingGravity.x,sa[r]=b*a.accelerationIncludingGravity.y,ta[r]=b*a.accelerationIncludingGravity.z):(Z[r]=0,sa[r]=0,ta[r]=0);null!=a.acceleration?(Za[r]=b*a.acceleration.x,$a[r]=b*a.acceleration.y,
ab[r]=b*a.acceleration.z):(Za[r]=0,$a[r]=0,ab[r]=0);null!=a.rotationRate?(Ca[r]=a.rotationRate.alpha*hb,Da[r]=a.rotationRate.beta*hb,Ea[r]=a.rotationRate.gamma*hb):(Ca[r]=0,Da[r]=0,Ea[r]=0);a=(new Date).getTime()-M;"undefined"===typeof ja||isNaN(ja)||(J=1E3*ja);a>J/2&&(D=Pa(r,J/a),ib=!0);r+=1;1==ba&&a>ec&&(a=D,D=r,L=!1,t({async:ia,CtxtEvent:"TRAFFIC",dataSize:r}),D=a,ba=!1);1==ib&&r>=D&&(0==Cb&&(t({async:ia,CtxtEvent:"RUNTIME",dataSize:D}),jb=(new Date).getTime()),M-jb>=K&&(t({async:ia,CtxtEvent:"RUNTIME",
dataSize:D}),jb=M),Cb+=1,r=0,ib=!1)}function Pa(a,b,c=!0){a=Math.round(a*b);if(c){c=1;if(!a||a&a-1)for(;c<a;)c<<=1;else c=a;b=a;var d=1;if(!b||b&b-1){for(;b>>=1;)d<<=1;b=d}a=c-a<a-b?c:b}a>y&&(a=y);return a}function Db(a="FIRST"){v.sampling=!0;if("undefined"!=typeof z)if(z.setReceptivity()){if("legacy"===R||Y())ba=!1}else ya()||Eb(),Y()&&(ka=1);"undefined"!==typeof screen&&(I.w=screen.width,I.y=screen.height,I.z=window.devicePixelRatio);Wb(a);r=0;if("DeviceMotionEvent"in window)try{gb&&eb(),window.addEventListener("devicemotion",
fb,!1),Q&&(Oa=setTimeout(ra,1E3)),setTimeout(window.removeEventListener,18E5,"devicemotion",fb)}catch(b){console.log("Contxtful.Api.log:",b)}else eb();1==da&&(a=Pa(Xa/1E3,Fb,!1),Ga.SetLength(a),Ha.SetLength(a),Ia.SetLength(a),Ja.SetLength(a),a=Pa(Ya/1E3,Gb,!1),Ka.SetLength(a),La.SetLength(a),document.addEventListener("mousemove",Hb,!1),document.addEventListener("touchmove",Ib,!1),document.addEventListener("mousedown",Jb),document.addEventListener("mouseup",Kb),document.addEventListener("touchstart",
Lb),document.addEventListener("touchend",Mb),Nb=setInterval(fc,1E3/Fb),Ob=setInterval(gc,1E3/Gb))}function ra(){Q&&(Sa(Math.floor(100*Math.random()),"Stop"),Q=!1);v.sampling&&(v.sampling=!1,t({noRawData:!0,async:!0,CtxtEvent:"STOP"}),window.removeEventListener("devicemotion",fb),1==da&&(document.removeEventListener("mousemove",Hb,!1),document.removeEventListener("touchmove",Ib,!1),document.removeEventListener("mouseup",Kb),document.removeEventListener("mousedown",Jb),document.removeEventListener("touchend",
Mb),document.removeEventListener("touchstart",Lb),clearInterval(Nb),clearInterval(Ob)),null!=U&&(clearInterval(U),U=null),null!=V&&(clearInterval(V),L=!1))}function Eb(){if("undefined"!=typeof z)try{z.callbackInjection("-1",z.getLookAlike())?X()||(Va(),oa(JSON.stringify(z.getLookAlike()))):Pb()}catch(a){Pb()}}function Pb(){Qb++;2>=Qb&&setTimeout(function(){Eb()},500)}function Bb(){ea=[];S=[];fa=[];O=[];ha=[]}function Hb(a){kb=Math.round(a.clientX);lb=Math.round(a.clientY)}function Ib(a){kb=Math.round(a.touches[0].clientX);
lb=Math.round(a.touches[0].clientY)}function gc(){Ka.push(kb);La.push(lb)}function Kb(a){S.push(Math.round(a.clientX));fa.push(Math.round(a.clientY));ha.push(a.button);O.push((new Date).getTime());ea.push(Qa.MouseUp)}function Jb(a){S.push(Math.round(a.clientX));fa.push(Math.round(a.clientY));ha.push(a.button);O.push((new Date).getTime());ea.push(Qa.MouseDown)}function Mb(a){S.push(Math.round(a.changedTouches[a.changedTouches.length-1].clientX));fa.push(Math.round(a.changedTouches[a.changedTouches.length-
1].clientY));ha.push(a.changedTouches[a.changedTouches.length-1].identifier);O.push((new Date).getTime());ea.push(Qa.TouchUp)}function Lb(a){S.push(Math.round(a.touches[a.touches.length-1].clientX));fa.push(Math.round(a.touches[a.touches.length-1].clientY));ha.push(a.touches[a.touches.length-1].identifier);O.push((new Date).getTime());ea.push(Qa.TouchDown)}function fc(){var a=window,b="inner";"innerWidth"in window||(b="client",a=document.documentElement||document.body);var c=a[b+"Width"];a=a[b+"Height"];
Ga.push(Math.round(window.pageXOffset));Ha.push(Math.round(window.pageYOffset));Ia.push(Math.round(hc+c));Ja.push(Math.round(ic+a))}var v={cicalls:[],ptim:[],clc:0,sicalls:[]},F=document.currentScript.getAttribute("src");try{var va="true"===(E(F).dry||!1);va&&console.log("Running in dry mode")}catch(a){console.log(a),va=!1}var Q=!1,H={fld:"",type:"",cat1:"",cat2:""};if(Q)try{H.fld=E(F).fld||"",H.type=E(F).type||"",H.cat1=E(F).cat1||"",H.cat2=E(F).cat2||""}catch(a){console.log(a),H.fld="",H.type="",
H.cat1="",H.cat2=""}var J=1E3,D=Pa(32*J/1E3,2);class la{constructor(a){this.SetLength(a)}SetLength(a){this.array=new Float32Array(a);this.length=a;this.cursize=this.idx=0}push(a){this.array[this.idx]=a;this.idx=(this.idx+1)%this.length;this.cursize<=this.length&&this.cursize++}resetBuffers(){this.cursize=this.idx=0}read(){if(this.cursize<this.length)var a=this.array.slice(0,this.cursize);else{if(0==this.idx)return this.array;var b=this.array.slice(0,this.idx),c=this.array.slice(this.idx,this.length);
a=new Float32Array(this.length);a.set(c,0);a.set(b,c.length)}return a}}var l={},zb={},Aa={},I={},Ba={},M=0,cc=-1,Ra="Y",ma=0,ja=1,ua=100,bb="cracq",cb="ctxtfl.com",Ma="ctxtfl.com";cb=x("PostDomain",cb)+"/";Ma=x("PostDomain",Ma)+"/";bb=x("PostPath",bb);var Zb=!1,za=40,Na=0,db=5,R="legacy",mb=!1;db=x("DesktopMaxPost",db);Na=x("DesktopPercentage",Na);mb=x("DesktopEnabled",mb);R=x("CertificationMode",R);"undefined"!=typeof contxtful_config&&contxtful_config.hasOwnProperty("manual")&&1==
contxtful_config.manual&&(R="high-precision");var ia=!0,ba=!0,ka=0,xb=!0,bc=16,ac=4,qa=function(){var a="undefined"!=typeof contxtful_config?contxtful_config.tag_id:E(F).id;if(20<a.length){var b=a.substring(0,1);switch(b){case "1":var c=a.substring(2,6);switch(b){case "1":if(b=4==c.length)b:{for(b=0;4>b;b++){var d=c[b].charCodeAt();if(d<"0".charCodeAt()||d>"9".charCodeAt()&&d<"A".charCodeAt()||d>"Z".charCodeAt()&&d<"a".charCodeAt()||d>"z".charCodeAt()){b=!1;break b}}b=!0}if(b){b="";for(d=0;d<c.length;d++){var f=
c[d].charCodeAt(),e=f-"0".charCodeAt();10<e&&(e=90<f?e-13:e-7);e=e.toString(2);f=Array(8-e.length+1).join("0")+e;b+=f}d=b.substring(2,3);f=b.substring(3,8);c=b.substring(12,16);b=b.substring(20,24);Ra="0"!=d?"Y":"N";d=parseInt(f,2);0>4*d-3?d=0:(d=Math.floor(4*d-3),100<d&&(d=100));ua=d;c=parseInt(c,2);ma=1E3*Math.pow(2,c);c=parseInt(b,2);ja=250*Math.pow(2,c)/1E3}}}}c=E(window.location.href).id;return a||c||""}(),yb=!1;Ra=x("Recep",Ra);ua=x("Percentage",ua);ma=1E3*x("Delay",ma/1E3);ja=x("WindowSize",
1E3*ja)/1E3;Ra.localeCompare("N")||(l.Rr="N");40<za&&(za=40);var T=function(a){"undefined"==typeof T.counter&&(T.counter=0);T.counter+=1;a.hasOwnProperty("Ok")&&(A.Ok="Use Contxtful.Api.Status",A.Status=a.Ok,101!=A.Status&&103!=A.Status||ra());a.hasOwnProperty("Data")&&(A.Data=a.Data);a.hasOwnProperty("likeliness")&&(A.likeliness=a.likeliness);a.hasOwnProperty("Recep")&&(Q&&(Sa(parseInt(a.Recep),"Post"),Q=!1),"undefined"!=typeof z&&(Y()?0!=ka?(1==ka&&ya()?z.callBack(a.Recep):(z.callbackInjection(a.Recep),
oa(a.Recep)),ka=0):oa(a.Recep):z.callBack(a.Recep)));A.Count=T.counter},P=[],Ua=0,hb=3.1416/180,ob=function(){X()?ya()&&nb():(null!=V&&clearInterval(V),V=setInterval(nb,K),setTimeout(function(){clearInterval(V);L=!1},18E5))},nb=function(){if(L){var a=wa("GET",jc+"?id="+qa,!0);a.onload=function(){var b=ub(a.response).GetStr(a.response.byteLength);Y()?ya()&&1==ka&&(ka=2,z.injectLookalike(b)):z.injectLookalike(b);oa(JSON.stringify(b))};a.onerror=function(){console.log("error in get")};a.send()}else clearInterval(V)},
y=256,Cb=0,ib=!1,ec=200,pb=!0;pb="false"==E(F).start?!1:pb;var K=parseInt(E(F).pdelay),jb=(new Date).getTime(),Xb=x("CreationTimeStamp","NoDate"),qb=1,jc="https://run.cntxtfl.com",L=!0,Qb=0,V=null;"undefined"!==typeof ua&&(qb=ua);var Wa=100>qb?!tb(qb):!1,da=!0,Oa=!1;v.sampling=!1;K=void 0===K||isNaN(K)?8E3:1E3>=K?1E3:5E3<=K?5E3:8E3;void 0==ma||isNaN(ma)||(K=ma);var Z=new Float32Array(y),sa=new Float32Array(y),ta=new Float32Array(y),Za=new Float32Array(y),$a=new Float32Array(y),ab=new Float32Array(y),
Ca=new Float32Array(y),Da=new Float32Array(y),Ea=new Float32Array(y),r=0;l.uaStr="NaN";l.screenW="NaN";l.screenH="NaN";l.color="NaN";l.dpi="NaN";l.ctxtReq=pa(zb);l.lang="NaN";var gb=null,U=null,hc=null,ic=null,kb=null,lb=null,Ga=new la(y),Ha=new la(y),Ia=new la(y),Ja=new la(y),Ka=new la(y),La=new la(y),Xa=x("WindowSize_fov",1E3),Ya=x("WindowSize_pointer",1E3),Fb=x("Freqency_fov",16),Gb=x("Freqency_pointer",16),S=[],fa=[],O=[],ha=[],ea=[],Nb=null,Ob=null,Qa={MouseDown:0,MouseUp:1,TouchDown:2,TouchUp:3},
W=new function(){function a(c,d){var f="Other";/Linux/.test(c)&&(f="Linux");/Windows/.test(c)&&(f="Windows");/Macintosh/.test(c)&&(f="Mac OS X");/iPad/.test(c)&&!/HiPad/.test(c)&&(f="iOS");/iPhone/.test(c)&&(f="iOS");/Android/.test(c)&&(f="Android");/CrOS/.test(c)&&(f="Chrome OS");d&&(/Windows Phone/.test(c)&&(f="Windows Phone"),/Ubuntu/.test(c)&&(f="Ubuntu"),/Fedora/.test(c)&&(f="Fedora"),/Tizen/.test(c)&&(f="Tizen"),/CrKey/.test(c)&&(f="Chromecast"),/FreeBSD/.test(c)&&(f="FreeBSD"),/OpenBSD/.test(c)&&
(f="OpenBSD"),/\(BB10;/.test(c)&&(f="BlackBerry OS"),/Web0S/.test(c)&&(f="Web0S"));return f}function b(c,d){var f=a(c,d);f=/Mac OS X|Linux|Windows|Chrome OS|Ubuntu|Fedora|Chromecast|OpenBSD/.test(f);d&&/NetCast|Fuchsia|Andr0id|Android/.test(c)&&(f=!1);return f}return{isMobile:function(c=!0){let d=navigator.userAgent;var f;if(!(f=b(d,c))){let e=/Other|Tizen|OpenBSD|FreeBSD|Web0S/;f=!0;if(/Mobile /.test(d)||e.test(a(d,c))||b(c))f=!1;/iPhone/.test(d)&&(f=!1);/iPad/.test(d)&&(f=!0);c&&(/Mobile Midori|Mobile DuckDuckGo|Mobile Iron/.test(d)&&
(f=!0),/NetCast|Fuchsia|Andr0id|; rv:/.test(d)&&(f=!1),/Silk|ARM/.test(d)&&(f=!0),/Quest/.test(d)&&/Mobile/.test(d)&&(f=!0),/\(Linux; Android\)/.test(d)&&(f=!1),/ zh-cn;/.test(d)&&(f=!0))}return f||/http/.test(d)?!1:!0},isApple:function(){return/iPad|iPhone|iPod/.test(navigator.userAgent)||/Macintosh|Mac OS/.test(navigator.userAgent)}}};v.isMobile=W.isMobile();var z=new function(){function a(e,k={}){var g=!1,h;let m=!1;try{var n=parseInt(e)}catch(u){na("[CONTXTFUL] ERROR: "+u+". Receptivity not an numerical value."),
n=-1}-1!=n&&"number"==typeof n&&L&&(L=!1);if("undefined"!==typeof k.M){var p=h="";if("undefined"!==typeof W&&"object"==typeof W)if(W.isMobile())var q=k.M;else q=k.D,m=!0;else q=k.D;"N"==q?(q="No",p="NonReceptive"):(q="Yes",p="Receptive")}else 0>n?(h="",p="NonReceptive",q="No"):33>=n?(h="low",p="NonReceptive",q="No"):(h=66>=n?"average":"premium",p="Receptive",q="Yes");if("undefined"!=typeof contxtful_config){n=contxtful_config.callback||"";var w=contxtful_config.SSP||"GAM"}else n=E(F).callback||"",
w=E(F).SSP||"GAM";m&&!mb&&(p="NonReceptive");var C={receptivity:e,ReceptivityState:p,receptivity_range:h,ReceptivityLookalike:q};if("undefined"!==typeof k.RETURN&&!0===k.RETURN)return C;if(""!=n)if(e=n.split("."),5>=e.length)try{if(1==e.length)window[e[0]](C);else if(2==e.length)window[e[0]][e[1]](C);else if(3==e.length)window[e[0]][e[1]][e[2]](C);else if(4==e.length)window[e[0]][e[1]][e[2]][e[3]](C);else if(5==e.length)window[e[0]][e[1]][e[2]][e[3]][e[4]](C);g=!0;v.cicalls.push(["CC",performance.now().toFixed(0)]);
v.callbackSetup=!0}catch(u){na("[CONTXTFUL INJECTION] ERROR caught: "+u+" for input : "+n)}else v.callbackSetup=!1,na("[CONTXTFUL INJECTION] ERROR: window."+n+"(str) is undefined"),na("[CONTXTFUL INJECTION] HINT: Make sure to add the callback=domain.function to the <script>."),na("[CONTXTFUL INJECTION] HINT: Make sure the callback is accessible at the window level, accepts only 1 STR value and is more than 5 layers deep.");else if("indexexchange"==w.toLowerCase())try{window.headertag.cmd.push(function(){window.headertag.setSiteKeyValueData(C)}),
g=!0,v.cicalls.push(["IX",performance.now().toFixed(0)]),v.IXinjection=!0}catch(u){v.IXinjection=!1}else try{window.googletag.cmd.push(function(){Object.keys(C).forEach(u=>{window.googletag.pubads().setTargeting(u,C[u])})}),v.cicalls.push(["GAM",performance.now().toFixed(0)]),g=v.GAMinjection=!0}catch(u){v.GAMinjection=!1}return g}function b(e,k={}){e=a(e,k);0==e||!Y()&&"legacy"!==R||(Va(),L=!1);return e}function c(e,k={}){e=e.replace(/"/g,"");e=e.replace(/'/g,'"');let g={};try{g=JSON.parse(e)}catch(h){g=
{}}Object.assign(g,k);k=a("-1",g);Y()&&0!=k&&Va();return k}var d=x("lookalikeParameter","{'M':'N', 'D':'N'}");"undefined"!=typeof contxtful_config&&(d="{'M':'N', 'D':'N'}");var f=d.replace(/"/g,"");f=f.replace(/'/g,'"');try{d=JSON.parse(f)}catch(e){d={}}return{setReceptivity:function(e={}){var k=null!==sessionStorage.getItem("ctxtflrec")?Date.now()<sessionStorage.getItem("ctxtflexp"):!1;return k&&(k=sessionStorage.getItem("ctxtflrec"),null!=k)?isNaN(parseInt(k))?c(k,e):b(k,e):!1},callbackInjection:a,
callBack:function(e){b(e);oa(e)},getLookAlike:function(){return d},injectLookalike:c}},A=new function(){return{SetId:function(a){this.userId=a},GetId:function(){return this.userId},SetUserField:function(a,b){Aa[a]=b},ClearUserField:function(){Aa={}},GetUserField:function(a){return Aa[a]},SetCampaignParam:function(a,b){Ba[a]=b},ClearCampaignParam:function(){Ba={}},GetCampaignParam:function(a){return Ba[a]},SetReceptivity:function(){X()?A.GetManualReceptivity():"undefined"!=typeof z&&z.setReceptivity()},
GetReceptivity:function(){return X()?(sb(),!1):"undefined"!=typeof z?z.setReceptivity({RETURN:!0}):!1},TriggerEvent:function(a){var b="no_Valid_parameter";if("string"===typeof a||"object"===typeof a)b=a;I.Trigger=b;t({CtxtEvent:"TRIGGER",async:ia,dataSize:r});I={}},GetManualReceptivity:function(){X()?L?nb():t({CtxtEvent:"MANUAL",async:ia,dataSize:r}):sb()}}};A.Results={"Attention Level":{Confidence:"Contact Contxtful",State:"Contact Contxtful"},"Device Movement":{Confidence:"Contact Contxtful",State:"Contact Contxtful"},
"Holding In Hand":{Confidence:"Contact Contxtful",State:"Contact Contxtful"}};A.Modules={attention:{Level:"Contact Contxtful",State:"Contact Contxtful"},humanity:{Level:"Contact Contxtful",State:"Contact Contxtful"},movement:{Level:"Contact Contxtful",State:"Contact Contxtful"}};A.Data={Att:{Lv:"Contact Contxtful",St:"Contact Contxtful"},InHand:{Lv:"Contact Contxtful",St:"Contact Contxtful"},Mvt:{Lv:"Contact Contxtful",St:"Contact Contxtful"}};A.Response="Contact Contxtful";A.userId="Contact Contxtful";
A.Recep="Contact Contxtful";l.userIdInternal="1722249c920e6474";"undefined"!=typeof contxtful_config?(l.userIdInternal=Tb(),l.userIdClient=contxtful_config.userIdClient):l.userIdClient=E(F).userId;A.userId=l.userIdInternal;l.dataSampled="Y";"undefined"!==typeof W&&"object"==typeof W&&(gb=W.isApple());pb&&Db();var Rb=J;"undefined"!=typeof contxtful_config&&(Rb=0);"undefined"!==typeof ob&&"function"==typeof ob&&setTimeout(function(){L&&ob()},Rb);return{tests:v,Api:A,Start:Db,Stop:ra}};

// CreationDate:11-21-2022-20:18:17
